var Comps=function(i){"use strict";var h=Object.defineProperty;var w=(i,s,r)=>s in i?h(i,s,{enumerable:!0,configurable:!0,writable:!0,value:r}):i[s]=r;var c=(i,s,r)=>(w(i,typeof s!="symbol"?s+"":s,r),r);let s=[];function r(l){l.forEach(function(n){n&&typeof n.render=="function"&&(s.includes(n)||s.push(n))}),_()}function _(){Promise.resolve().then(function(){s.forEach(l=>{typeof l.render=="function"&&l.render(),s=[],_()})})}function d(l){let n=l,t=[];return{get value(){const e=window.__curContext__,o=window.__curEffect__;return e&&(t.includes(e)||t.push(e)),o&&(t.includes(o)||t.push(o)),n},set value(e){n=e,r(t)}}}function u(l){const n={__effect__:!0,render:null};window.__curEffect__=n,typeof l=="function"?(n.render=l,n.render()):console.error("effect接收一个函数"),window.__curEffect__=null}class f extends HTMLElement{constructor(){super();c(this,"__config__");c(this,"__conponent__");c(this,"props")}defineProps(t={initProps:{}}){this.__conponent__=!0,this.__config__=t,this.props={...t.initProps};let e=this;window.addEventListener("load",function(){Object.keys(e.props).forEach(o=>{console.log(window[e.getAttribute(o)||""]),console.dir(e),e.props[o]=window[e.getAttribute(o)||""]||e.props[o]}),e.render()})}defineTemplate(){return""}render(){window.__curContext__=this;const t=this.defineTemplate.bind(this)();this.innerHTML=typeof t=="string"?t:"",window.__curContext__=null}}const v="",m="";class a extends f{constructor(){super();c(this,"__config__");c(this,"props");this.defineProps({initProps:{datalist:null}})}handleDeleteSelf(){console.log("111111111111")}defineTemplate(){const{datalist:t}=this.props;let e="";return Array.isArray(t.value)?e=t.value.length?t.value.map((o,p)=>`
            <div class="comp-showlist__item">
              <div class="comp-showlist__title">${o.label}</div>
              <div class="comp-showlist__num">${o.value}</div>
              <div class="comp-showlist__close" onclick="handleDelete(${p},'${o.label}')">Delete</div>
            </div>
          `).join(""):'<div class="comp-showlist__empty">暂无数据</div>':e='<div class="comp-showlist__loading">loading...</div>',`
      <style> p {color: white;} /*这里也可以写样式但是不建议这样写,可以写到单独的.less文件中*/ </style>
      <div class="comp-showlist">${e}</div>
    `}}return customElements.define("show-list",a),i.BaseComponent=f,i.Ref=d,i.effect=u,Object.defineProperty(i,Symbol.toStringTag,{value:"Module"}),i}({});
